Remove registry method to product page view block
alma/alma-monthlypayments-magento2 pull request #15
Opened 2022-01-07 12:43 UTC by Francois-Gomis

2022-01-07 16:22 UTC, syjust requested changes

2022-01-07 16:22 UTC, syjust commented on Block/Catalog/Product/View.php
> +        array $data = [],
Sonar n'est pas content que cet argument optionnel vienne se mettre avant des arguments requis ;)

2022-01-07 16:22 UTC, syjust commented on Block/Catalog/Product/View.php
> +            $this->product = $this->dataHelper->getProduct();
Du coup, tu n'en profites pas pour tester si `$this->product` est `null` après l'avoir récupéré du `dataHelper` ?

2022-01-07 16:22 UTC, syjust commented on Block/Catalog/Product/View.php
> +        if(is_null($this->product)){
pour éviter la complexité cyclomatique, il vaut mieux `return` asap `if (!is_null($this->product))` plutôt que d'imbriquer les `if { if { if {`

2022-01-07 16:22 UTC, syjust commented on Block/Catalog/Product/View.php
>      private function getProduct()
on en profiterai pas pour refactoriser cette méthode en `initProduct` (ça fait bizarre un getter qui ne return rien)

2022-01-10 09:40 UTC, syjust approved these changes

2022-01-10 09:40 UTC, syjust commented on Block/Catalog/Product/View.php
> +        if(is_null($this->product)){
Du coup plus besoin de tester le `getId()` ?

2022-01-10 11:11 UTC, Francois-Gomis commented
Au vue de la provenance des données, Je ne pense pas que  $this->product puisse être null (mais c'est une bonne chose de le vérifier )  ou même empty. L'interface nous protège donc d'un this->product->getId() qui serait non conforme.

2022-02-16 17:37 UTC, syjust approved these changes

2022-09-06 08:01 UTC, closed without merging