fix : Alma client is not defined in BO
alma/alma-monthlypayments-magento2 pull request #49
Opened 2022-07-12 08:30 UTC by Francois-Gomis

2022-07-12 08:50 UTC, syjust-alma approved these changes

2022-07-12 09:02 UTC, syjust-alma reviewed
I think the better way to manage this `InvalidArgumenException` will be to throw it directly from `getDefaultClient()` ...

As I can see, it could be used everywhere it needed by changing the __constructor assignation to `$this->alma = $almaClient` ... then, you will be able to use `$this->alma->getDefaultClient()->whatYouWant()` after and try catch on `InvalidArgumentException` where it is needed.

Finally, I think `InvalidArgumentException` could be replaced by a specific `AlmaDefaultClientException` or somthing like that 😉

2022-07-12 09:02 UTC, syjust-alma requested changes
I think the better way to manage this `InvalidArgumenException` will be to throw it directly from `getDefaultClient()` ...

As I can see, it could be used everywhere it needed by changing the __constructor assignation to `$this->alma = $almaClient` ... then, you will be able to use `$this->alma->getDefaultClient()->whatYouWant()` after and try catch on `InvalidArgumentException` where it is needed.

Finally, I think `InvalidArgumentException` could be replaced by a specific `AlmaDefaultClientException` or somthing like that 😉

2022-07-12 15:41 UTC, syjust-alma approved these changes

2022-07-12 15:41 UTC, syjust-alma commented on Gateway/Config/PaymentPlans/PaymentPlansConfig.php
> +        } catch (RequestError | AlmaClientException $e) {
😍

2022-07-12 15:41 UTC, syjust-alma commented on Gateway/Http/Client/RefundClient.php
> +            $this->logger->error("Error creating refund:", [$e->getMessage()]);
warning, sometime, getMessage is empty in `RequestError`

with [php-client 1.9.0](https://github.com/alma/alma-php-client/releases/tag/v1.9.0), you can now use `getErrorMessage`

2022-07-19 09:12 UTC, merged

2022-07-19 09:19 UTC, Francois-Gomis commented on Gateway/Validator/RefundResponseValidator.php
> +            if ($apiResponse->responseCode == '460') {
I create custom response code for custom error message in backend