MPP-123 add Basket items in cart
alma/alma-monthlypayments-magento2 pull request #93
Opened 2023-04-14 15:16 UTC by Francois-Gomis

2023-04-18 09:40 UTC, Benjamin-Freoua-Alma approved these changes

2023-04-20 07:40 UTC, ClaireAlma commented on Gateway/Request/CartDataBuilder.php
> +class CartDataBuilder implements BuilderInterface
manque commentaire de class

2023-04-20 07:50 UTC, ClaireAlma requested changes

2023-04-20 07:50 UTC, ClaireAlma commented on Gateway/Request/CartDataBuilder.php
> + * @copyright 2018-2019 Alma SAS
copryright 2019?

2023-04-20 07:50 UTC, ClaireAlma commented on Gateway/Request/CartDataBuilder.php
> +        $url = '';
tu peux aussi écrire comme ça 
```
        try {
            return $this->storeManager->getStore()->getBaseUrl(UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $path;
        } catch (NoSuchEntityException $e) {
            $this->logger->warning('Error in get media base url:', [$e->getMessage()]);
        }

        return '';
```

2023-04-20 07:50 UTC, ClaireAlma commented on Gateway/Request/CartDataBuilder.php
> +                $name = $this->categoryRepository->get($id)->getName();
en général il est plus couteux de faire une boucle pour requeter chaque name, que de requeter en une seule fois et de boucler sur les résultats pour construire le tableau

2023-04-20 07:50 UTC, ClaireAlma commented on Helpers/Functions.php
> +    public static function getPaymentType(string $planKey): string
commentaire de finction

2023-04-24 07:51 UTC, joyet-simon approved these changes

2023-05-19 14:08 UTC, Francois-Gomis commented on Gateway/Request/CartDataBuilder.php
> +        $url = '';
Done

2023-05-19 14:08 UTC, Francois-Gomis commented on Gateway/Request/CartDataBuilder.php
> +                $name = $this->categoryRepository->get($id)->getName();
Collection

2023-05-19 14:11 UTC, Francois-Gomis commented on Helpers/Functions.php
> +            $installmentCount = $matches[1];
`        if ($isKnownType) {
`
vérifie l'existance des matches

2023-05-22 11:45 UTC, ClaireAlma commented on Test/Unit/Helpers/ProductHelperTest.php
> +class ProductHelperTest extends TestCase
ca manque de retours à le ligne entre les fonctions et de commentaires de fonction ;)

2023-05-22 11:45 UTC, ClaireAlma approved these changes

2023-06-05 14:14 UTC, Francois-Gomis commented on Test/Unit/Helpers/ProductHelperTest.php
> +class ProductHelperTest extends TestCase
done

2023-06-05 15:02 UTC, merged